{
 "title": "per_Cell_stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "PDCP Bytes DL for Cells 1-6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"cu-up-cell-1_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter  "
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"cu-up-cell-2_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"cu-up-cell-3_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"cu-up-cell-4_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"cu-up-cell-5_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"cu-up-cell-6_m_pdcpbytesdl (celldltxvolume)\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell Average Latency",
   "type": "timeseries",
   "description": "pdcpLatency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Cell 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-1_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-2_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-3_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-4_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-5_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-6_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    }
   ]
  },
  {
   "title": "Cell Average Latency",
   "type": "timeseries",
   "description": "pdcpLatency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Cell 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-1_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-2_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-3_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-4_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-5_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-6_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    },
    {
     "alias": "Cell 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM \"cu-up-cell-1_drb.pdcpsdudelaydl (cellaveragelatency)\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    }
   ]
  },
  {
   "title": "PRB Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_dlprbusage\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Active UE DL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_drb.meanactiveuedl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 7",
     "query": "SELECT \"value\" FROM \"du-cell-7_drb.meanactiveuedl\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RRU PRB Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_rru.prbuseddl\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total DL Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Error Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total  number of DL initial TBs  DL 64 QAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_tb.totnbrdlinitial.64qam\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total  number of DL initial TBs  DL 16QAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_tb.totnbrdlinitial.16qam\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total  number of DL initial TBs  DL QPSK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "Cell 1",
     "query": "SELECT \"value\" FROM \"du-cell-1_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 2",
     "query": "SELECT \"value\" FROM \"du-cell-2_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 3",
     "query": "SELECT \"value\" FROM \"du-cell-3_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 4",
     "query": "SELECT \"value\" FROM \"du-cell-4_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 5",
     "query": "SELECT \"value\" FROM \"du-cell-5_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "Cell 6",
     "query": "SELECT \"value\" FROM \"du-cell-6_tb.totnbrdlinitial.qpsk.ueid\" WHERE $timeFilter"
    }
   ]
  }
 ]
}